### ISSUE TITLE
Manual port number

### ISSUE THREAD

**Issue by vandenbrakel** [seanksullivan/Wemo.net#3]
Does this work with Wemo's with a non default port?  Like this? 

x.TurnOffWemoPlugAsync("http://192.168.86.39:3000").GetAwaiter().GetResult();

Thanks.

**Comment by seanksullivan** [comment]
That call would not work, since the Port value is set within the WemoPlug class (as a public set/get property).  This is a fairly simple addition - I will add it.

**Comment by seanksullivan** [comment]
Updated code to allow for a custom Port value.
