### ISSUE TITLE
Issue with this on a Raspberry Pi and .NET core

### ISSUE THREAD

**Issue by jibylotas** [seanksullivan/Wemo.net#7]
For some reason in .NET core on a linux (Stretch Raspbian) system the find devices fails because the timeout is not caught as a webexception.  I added a handler for a generic exception and it seems to work fine now

Here is the code

    private static bool VerifyWemoDevice(HttpWebRequest request, string reqContentSoap)
        {
            var response = false;
            try
            {
                // Write the Soap Request to the Request Stream
                using (var requestStream = request.GetRequestStream())
                {
                    var encoding = new UTF8Encoding();
                    requestStream.Write(encoding.GetBytes(reqContentSoap), 0, encoding.GetByteCount(reqContentSoap));

                    // Send the Request and acquire the Response
                    using (var httpResponse = request.GetResponse() as HttpWebResponse)
                    {
                        var headers = httpResponse.Headers;
                        var headerValues = headers.GetValues("X-User-Agent").ToList();

                        if (headerValues.Exists(x => x.Contains("redsonic")))
                        {
                            response = true;
                        }
                    }
                }
            }
            catch (WebException ex)
            {
                response = false;
            }
            catch (Exception err)
            {
                //For some reason in .NET core on a linux system this is not caught as a Web Exception
                //This is a catch all for all exceptions that may occur
                response = false;
            }

            return response;
        }

**Comment by seanksullivan** [comment]
Good info!  I haven't tested on my Raspberry Pi - but I will now.
